# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greet_pb2 as greet__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSNL = channel.unary_unary(
                '/greet.Greeter/GenerateSNL',
                request_serializer=greet__pb2.SNLRequest.SerializeToString,
                response_deserializer=greet__pb2.SNLReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def GenerateSNL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSNL': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSNL,
                    request_deserializer=greet__pb2.SNLRequest.FromString,
                    response_serializer=greet__pb2.SNLReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def GenerateSNL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/GenerateSNL',
            greet__pb2.SNLRequest.SerializeToString,
            greet__pb2.SNLReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
