# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"/\n\nSNLRequest\x12\r\n\x05resps\x18\x01 \x01(\t\x12\x12\n\ndictionary\x18\x02 \x01(\t\"J\n\x08SNLReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05\x12\x0c\n\x04warn\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\x05\x12\x0f\n\x07results\x18\x04 \x01(\t2<\n\x07Greeter\x12\x31\n\x0bGenerateSNL\x12\x11.greet.SNLRequest\x1a\x0f.greet.SNLReplyB\x0e\xaa\x02\x0bGrpcGreeterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\013GrpcGreeter'
  _globals['_SNLREQUEST']._serialized_start=22
  _globals['_SNLREQUEST']._serialized_end=69
  _globals['_SNLREPLY']._serialized_start=71
  _globals['_SNLREPLY']._serialized_end=145
  _globals['_GREETER']._serialized_start=147
  _globals['_GREETER']._serialized_end=207
# @@protoc_insertion_point(module_scope)
